language: ruby
rvm:
  - 2.4.3
  - 2.3.6
  - ruby-head
  - jruby-9
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-9
    - rvm: jruby-head
  fast_finish: true
before_install:
  - gem install bundler:1.17.3
  - bundle _1.17.3_ install --jobs=3 --retry=3
script: "bundle _1.17.3_ exec rake"
